### ISSUE TITLE
Client is required does not show when no client selected

### ISSUE THREAD

**Issue by charkour** [cqlcorp/benchmark#226]
To reproduce, edit a project and click send evaluations. Add a client which will make "client is required" text disappear. Click send evaluations. Remove the client. Click send evaluation and the error text stating "client is required" will not show up again.

This is an extreme edge case so we should focus our efforts else-where for now.

**Comment by jonathanchaffer** [comment]
This happens because the value of the `client` only changes when you select an item in the autocomplete menu. A similar bug happens in the team member list – if you select a team member name, then change the text field, it will still treat the team member as having been selected. A possible solution to this is to unset the fields when the text input changes.

**Comment by charkour** [comment]
Sounds good!
